name: Just Swim

on:
  push:
    branches: [main]
    # Action을 작동시킬 브랜치
    # 여러개 가능 (develop 브랜치로 먼저 개발하고 main에 적용시키는게 안전하다.)

env:
  DOCKER_IMAGE: ghcr.io/YOONSOO7429/justswim
  VERSION: ${{ github.sha }}
  NAME: justswim

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Generate Environment Variables File for Production
        run: |
          echo "KAKAO_ID=$KAKAO_ID" >> .env
          ehco "NAVER_ID=$NAVER_ID" >> .env
          echo "NAVER_SECRET=$NAVER_SECRET" >> .env
          echo "GOOGLE_ID=$GOOGLE_ID" >> .env
          echo "GOOGLE_SECRET=$GOOGLE_SECRET" >> .env
          echo "JWT_SECRET=$JWT_SECRET" >> .env
          echo "DB_HOST=$DB_HOST" >> .env
          echo "DB_DATABASE=$DB_DATABASE" >> .env 
          echo "DB_PORT=$DB_PORT" >> .env
          echo "DB_USERNAME=$DB_USERNAME" >> .env
          echo "DB_PASSWORD=$DB_PASSWORD" >> .env
          echo "AWS_REGION=$AWS_REGION" >> .env
          echo "AWS_S3_ACCESS_KEY=$AWS_S3_ACCESS_KEY" >> .env
          echo "AWS_S3_SECRET_ACCESS_KEY=$AWS_S3_SECRET_ACCESS_KEY" >> .env
          echo "AWS_S3_BUCKET_NAME=$AWS_S3_BUCKET_NAME" >> .env
          echo "SELECT_USERTYPE_REDIRECT_URI=$SELECT_USERTYPE_REDIRECT_URI" >> .env
          echo "HOME_REDIRECT_URI=$HOME_REDIRECT_URI" >> .env
        env:
          KAKAO_ID: ${{ secrets.KAKAO_ID }}
          NAVER_ID: ${{ secrets.NAVER_ID }}
          NAVER_SECRET: ${{ secrets.NAVER_SECRET }}
          GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          REDIRECT_URI_AUTH: ${{ secrets.SELECT_USERTYPE_REDIRECT_URI }}
          REDIRECT_URI_HOME: ${{ secrets.HOME_REDIRECT_URI }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache docker layers
        uses: actions/cache@v2
        with:
          path: /
